dist: xenial
services: docker

language: go
go:
  - 1.13.x

before_script:
  - export VPP_IMG="ligato/vpp-base:master"
  - docker pull $VPP_IMG

script:
  - bash ./genbinapi.sh
  - go test -v ./binapi/...

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
