dist: xenial
services: docker

language: go
go:
  - "1.12.x"

before_script:
  - export GO111MODULE=on
  - export VPP_IMG="ligato/vpp-base:master"
  - docker pull $VPP_IMG

script:
  - bash ./genbinapi.sh

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
