// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: binapis/vpp2001/.vppapi/core/ipip_types.api.json

/*
Package ipip_types is a generated VPP binary API for 'ipip_types' module.

It consists of:
	  1 enum
*/
package ipip_types

import (
	"bytes"
	"context"
	"io"
	"strconv"

	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "ipip_types"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0xa2a8fa8d
)

// IpipTunnelFlags represents VPP binary API enum 'ipip_tunnel_flags'.
type IpipTunnelFlags uint8

const (
	IPIP_TUNNEL_API_FLAG_NONE            IpipTunnelFlags = 0
	IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DF   IpipTunnelFlags = 1
	IPIP_TUNNEL_API_FLAG_ENCAP_SET_DF    IpipTunnelFlags = 2
	IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DSCP IpipTunnelFlags = 4
	IPIP_TUNNEL_API_FLAG_ENCAP_COPY_ECN  IpipTunnelFlags = 8
	IPIP_TUNNEL_API_FLAG_DECAP_COPY_ECN  IpipTunnelFlags = 16
)

var IpipTunnelFlags_name = map[uint8]string{
	0:  "IPIP_TUNNEL_API_FLAG_NONE",
	1:  "IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DF",
	2:  "IPIP_TUNNEL_API_FLAG_ENCAP_SET_DF",
	4:  "IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DSCP",
	8:  "IPIP_TUNNEL_API_FLAG_ENCAP_COPY_ECN",
	16: "IPIP_TUNNEL_API_FLAG_DECAP_COPY_ECN",
}

var IpipTunnelFlags_value = map[string]uint8{
	"IPIP_TUNNEL_API_FLAG_NONE":            0,
	"IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DF":   1,
	"IPIP_TUNNEL_API_FLAG_ENCAP_SET_DF":    2,
	"IPIP_TUNNEL_API_FLAG_ENCAP_COPY_DSCP": 4,
	"IPIP_TUNNEL_API_FLAG_ENCAP_COPY_ECN":  8,
	"IPIP_TUNNEL_API_FLAG_DECAP_COPY_ECN":  16,
}

func (x IpipTunnelFlags) String() string {
	s, ok := IpipTunnelFlags_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
