// Code generated by GoVPP binapi-generator. DO NOT EDIT.
//  source: binapi/virtio.api.json

/*
 Package virtio is a generated from VPP binary API module 'virtio'.

 It contains following objects:
	  6 messages
	  3 services

*/
package virtio

import "git.fd.io/govpp.git/api"
import "github.com/lunixbochs/struc"
import "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = struc.Pack
var _ = bytes.NewBuffer

// VlAPIVersion represents version of the binary API module.
const VlAPIVersion = 0x394fa590

// Services represents VPP binary API services:
//
//	"services": {
//	    "virtio_pci_create": {
//	        "reply": "virtio_pci_create_reply"
//	    },
//	    "sw_interface_virtio_pci_dump": {
//	        "reply": "sw_interface_virtio_pci_details",
//	        "stream": true
//	    },
//	    "virtio_pci_delete": {
//	        "reply": "virtio_pci_delete_reply"
//	    }
//	},
//
type Services interface {
	DumpSwInterfaceVirtioPci(*SwInterfaceVirtioPciDump) ([]*SwInterfaceVirtioPciDetails, error)
	VirtioPciCreate(*VirtioPciCreate) (*VirtioPciCreateReply, error)
	VirtioPciDelete(*VirtioPciDelete) (*VirtioPciDeleteReply, error)
}

/* Messages */

// VirtioPciCreate represents VPP binary API message 'virtio_pci_create':
//
//	"virtio_pci_create",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "client_index"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	[
//	    "u32",
//	    "pci_addr"
//	],
//	[
//	    "u8",
//	    "use_random_mac"
//	],
//	[
//	    "u8",
//	    "mac_address",
//	    6
//	],
//	[
//	    "u16",
//	    "tx_ring_sz"
//	],
//	[
//	    "u16",
//	    "rx_ring_sz"
//	],
//	[
//	    "u64",
//	    "features"
//	],
//	{
//	    "crc": "0x78e17a09"
//	}
//
type VirtioPciCreate struct {
	PciAddr      uint32
	UseRandomMac uint8
	MacAddress   []byte `struc:"[6]byte"`
	TxRingSz     uint16
	RxRingSz     uint16
	Features     uint64
}

func (*VirtioPciCreate) GetMessageName() string {
	return "virtio_pci_create"
}
func (*VirtioPciCreate) GetCrcString() string {
	return "78e17a09"
}
func (*VirtioPciCreate) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// VirtioPciCreateReply represents VPP binary API message 'virtio_pci_create_reply':
//
//	"virtio_pci_create_reply",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	[
//	    "i32",
//	    "retval"
//	],
//	[
//	    "u32",
//	    "sw_if_index"
//	],
//	{
//	    "crc": "0xfda5941f"
//	}
//
type VirtioPciCreateReply struct {
	Retval    int32
	SwIfIndex uint32
}

func (*VirtioPciCreateReply) GetMessageName() string {
	return "virtio_pci_create_reply"
}
func (*VirtioPciCreateReply) GetCrcString() string {
	return "fda5941f"
}
func (*VirtioPciCreateReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

// VirtioPciDelete represents VPP binary API message 'virtio_pci_delete':
//
//	"virtio_pci_delete",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "client_index"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	[
//	    "u32",
//	    "sw_if_index"
//	],
//	{
//	    "crc": "0x529cb13f"
//	}
//
type VirtioPciDelete struct {
	SwIfIndex uint32
}

func (*VirtioPciDelete) GetMessageName() string {
	return "virtio_pci_delete"
}
func (*VirtioPciDelete) GetCrcString() string {
	return "529cb13f"
}
func (*VirtioPciDelete) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// VirtioPciDeleteReply represents VPP binary API message 'virtio_pci_delete_reply':
//
//	"virtio_pci_delete_reply",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	[
//	    "i32",
//	    "retval"
//	],
//	{
//	    "crc": "0xe8d4e804"
//	}
//
type VirtioPciDeleteReply struct {
	Retval int32
}

func (*VirtioPciDeleteReply) GetMessageName() string {
	return "virtio_pci_delete_reply"
}
func (*VirtioPciDeleteReply) GetCrcString() string {
	return "e8d4e804"
}
func (*VirtioPciDeleteReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

// SwInterfaceVirtioPciDump represents VPP binary API message 'sw_interface_virtio_pci_dump':
//
//	"sw_interface_virtio_pci_dump",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "client_index"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	{
//	    "crc": "0x51077d14"
//	}
//
type SwInterfaceVirtioPciDump struct{}

func (*SwInterfaceVirtioPciDump) GetMessageName() string {
	return "sw_interface_virtio_pci_dump"
}
func (*SwInterfaceVirtioPciDump) GetCrcString() string {
	return "51077d14"
}
func (*SwInterfaceVirtioPciDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// SwInterfaceVirtioPciDetails represents VPP binary API message 'sw_interface_virtio_pci_details':
//
//	"sw_interface_virtio_pci_details",
//	[
//	    "u16",
//	    "_vl_msg_id"
//	],
//	[
//	    "u32",
//	    "context"
//	],
//	[
//	    "u32",
//	    "sw_if_index"
//	],
//	[
//	    "u32",
//	    "pci_addr"
//	],
//	[
//	    "u8",
//	    "mac_addr",
//	    6
//	],
//	[
//	    "u16",
//	    "tx_ring_sz"
//	],
//	[
//	    "u16",
//	    "rx_ring_sz"
//	],
//	[
//	    "u64",
//	    "features"
//	],
//	{
//	    "crc": "0xd3a3ade3"
//	}
//
type SwInterfaceVirtioPciDetails struct {
	SwIfIndex uint32
	PciAddr   uint32
	MacAddr   []byte `struc:"[6]byte"`
	TxRingSz  uint16
	RxRingSz  uint16
	Features  uint64
}

func (*SwInterfaceVirtioPciDetails) GetMessageName() string {
	return "sw_interface_virtio_pci_details"
}
func (*SwInterfaceVirtioPciDetails) GetCrcString() string {
	return "d3a3ade3"
}
func (*SwInterfaceVirtioPciDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func init() {
	api.RegisterMessage((*VirtioPciCreate)(nil), "virtio.VirtioPciCreate")
	api.RegisterMessage((*VirtioPciCreateReply)(nil), "virtio.VirtioPciCreateReply")
	api.RegisterMessage((*VirtioPciDelete)(nil), "virtio.VirtioPciDelete")
	api.RegisterMessage((*VirtioPciDeleteReply)(nil), "virtio.VirtioPciDeleteReply")
	api.RegisterMessage((*SwInterfaceVirtioPciDump)(nil), "virtio.SwInterfaceVirtioPciDump")
	api.RegisterMessage((*SwInterfaceVirtioPciDetails)(nil), "virtio.SwInterfaceVirtioPciDetails")
}
