// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: binapis/vpp1904/.vppapi/core/bier.api.json

/*
Package bier is a generated VPP binary API for 'bier' module.

It consists of:
	  3 types
	 22 messages
	 11 services
*/
package bier

import (
	"bytes"
	"context"
	"io"
	"strconv"

	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "bier"
	// APIVersion is the API version of this module.
	APIVersion = "1.1.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0x5b78fe13
)

// BierTableID represents VPP binary API type 'bier_table_id'.
type BierTableID struct {
	BtSet       uint8
	BtSubDomain uint8
	BtHdrLenID  uint8
}

func (*BierTableID) GetTypeName() string  { return "bier_table_id" }
func (*BierTableID) GetCrcString() string { return "435c691d" }

// FibMplsLabel represents VPP binary API type 'fib_mpls_label'.
type FibMplsLabel struct {
	IsUniform uint8
	Label     uint32
	TTL       uint8
	Exp       uint8
}

func (*FibMplsLabel) GetTypeName() string  { return "fib_mpls_label" }
func (*FibMplsLabel) GetCrcString() string { return "c93bf35c" }

// FibPath represents VPP binary API type 'fib_path'.
type FibPath struct {
	SwIfIndex         uint32
	TableID           uint32
	Weight            uint8
	Preference        uint8
	IsLocal           uint8
	IsDrop            uint8
	IsUDPEncap        uint8
	IsUnreach         uint8
	IsProhibit        uint8
	IsResolveHost     uint8
	IsResolveAttached uint8
	IsDvr             uint8
	IsSourceLookup    uint8
	IsInterfaceRx     uint8
	Afi               uint8
	NextHop           []byte `struc:"[16]byte"`
	NextHopID         uint32
	RpfID             uint32
	ViaLabel          uint32
	NLabels           uint8
	LabelStack        []FibMplsLabel `struc:"[16]FibMplsLabel"`
}

func (*FibPath) GetTypeName() string  { return "fib_path" }
func (*FibPath) GetCrcString() string { return "ba7a81f0" }

// BierDispEntryAddDel represents VPP binary API message 'bier_disp_entry_add_del'.
type BierDispEntryAddDel struct {
	BdeBp           uint16
	BdeTblID        uint32
	BdeIsAdd        uint8
	BdePayloadProto uint8
	BdeNPaths       uint8 `struc:"sizeof=BdePaths"`
	BdePaths        []FibPath
}

func (m *BierDispEntryAddDel) Reset()                        { *m = BierDispEntryAddDel{} }
func (*BierDispEntryAddDel) GetMessageName() string          { return "bier_disp_entry_add_del" }
func (*BierDispEntryAddDel) GetCrcString() string            { return "4260a077" }
func (*BierDispEntryAddDel) GetMessageType() api.MessageType { return api.RequestMessage }

// BierDispEntryAddDelReply represents VPP binary API message 'bier_disp_entry_add_del_reply'.
type BierDispEntryAddDelReply struct {
	Retval int32
}

func (m *BierDispEntryAddDelReply) Reset()                        { *m = BierDispEntryAddDelReply{} }
func (*BierDispEntryAddDelReply) GetMessageName() string          { return "bier_disp_entry_add_del_reply" }
func (*BierDispEntryAddDelReply) GetCrcString() string            { return "e8d4e804" }
func (*BierDispEntryAddDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierDispEntryDetails represents VPP binary API message 'bier_disp_entry_details'.
type BierDispEntryDetails struct {
	BdeBp           uint16
	BdeTblID        uint32
	BdeIsAdd        uint8
	BdePayloadProto uint8
	BdeNPaths       uint8 `struc:"sizeof=BdePaths"`
	BdePaths        []FibPath
}

func (m *BierDispEntryDetails) Reset()                        { *m = BierDispEntryDetails{} }
func (*BierDispEntryDetails) GetMessageName() string          { return "bier_disp_entry_details" }
func (*BierDispEntryDetails) GetCrcString() string            { return "b9b10a59" }
func (*BierDispEntryDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierDispEntryDump represents VPP binary API message 'bier_disp_entry_dump'.
type BierDispEntryDump struct {
	BdeTblID uint32
}

func (m *BierDispEntryDump) Reset()                        { *m = BierDispEntryDump{} }
func (*BierDispEntryDump) GetMessageName() string          { return "bier_disp_entry_dump" }
func (*BierDispEntryDump) GetCrcString() string            { return "b5fa54ad" }
func (*BierDispEntryDump) GetMessageType() api.MessageType { return api.RequestMessage }

// BierDispTableAddDel represents VPP binary API message 'bier_disp_table_add_del'.
type BierDispTableAddDel struct {
	BdtTblID uint32
	BdtIsAdd uint8
}

func (m *BierDispTableAddDel) Reset()                        { *m = BierDispTableAddDel{} }
func (*BierDispTableAddDel) GetMessageName() string          { return "bier_disp_table_add_del" }
func (*BierDispTableAddDel) GetCrcString() string            { return "7671b2cb" }
func (*BierDispTableAddDel) GetMessageType() api.MessageType { return api.RequestMessage }

// BierDispTableAddDelReply represents VPP binary API message 'bier_disp_table_add_del_reply'.
type BierDispTableAddDelReply struct {
	Retval int32
}

func (m *BierDispTableAddDelReply) Reset()                        { *m = BierDispTableAddDelReply{} }
func (*BierDispTableAddDelReply) GetMessageName() string          { return "bier_disp_table_add_del_reply" }
func (*BierDispTableAddDelReply) GetCrcString() string            { return "e8d4e804" }
func (*BierDispTableAddDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierDispTableDetails represents VPP binary API message 'bier_disp_table_details'.
type BierDispTableDetails struct {
	BdtTblID uint32
}

func (m *BierDispTableDetails) Reset()                        { *m = BierDispTableDetails{} }
func (*BierDispTableDetails) GetMessageName() string          { return "bier_disp_table_details" }
func (*BierDispTableDetails) GetCrcString() string            { return "d27942c0" }
func (*BierDispTableDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierDispTableDump represents VPP binary API message 'bier_disp_table_dump'.
type BierDispTableDump struct{}

func (m *BierDispTableDump) Reset()                        { *m = BierDispTableDump{} }
func (*BierDispTableDump) GetMessageName() string          { return "bier_disp_table_dump" }
func (*BierDispTableDump) GetCrcString() string            { return "51077d14" }
func (*BierDispTableDump) GetMessageType() api.MessageType { return api.RequestMessage }

// BierImpAdd represents VPP binary API message 'bier_imp_add'.
type BierImpAdd struct {
	BiTblID  BierTableID
	BiSrc    uint16
	BiNBytes uint8 `struc:"sizeof=BiBytes"`
	BiBytes  []byte
}

func (m *BierImpAdd) Reset()                        { *m = BierImpAdd{} }
func (*BierImpAdd) GetMessageName() string          { return "bier_imp_add" }
func (*BierImpAdd) GetCrcString() string            { return "5d62e9ce" }
func (*BierImpAdd) GetMessageType() api.MessageType { return api.RequestMessage }

// BierImpAddReply represents VPP binary API message 'bier_imp_add_reply'.
type BierImpAddReply struct {
	Retval  int32
	BiIndex uint32
}

func (m *BierImpAddReply) Reset()                        { *m = BierImpAddReply{} }
func (*BierImpAddReply) GetMessageName() string          { return "bier_imp_add_reply" }
func (*BierImpAddReply) GetCrcString() string            { return "d49c5793" }
func (*BierImpAddReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierImpDel represents VPP binary API message 'bier_imp_del'.
type BierImpDel struct {
	BiIndex uint32
}

func (m *BierImpDel) Reset()                        { *m = BierImpDel{} }
func (*BierImpDel) GetMessageName() string          { return "bier_imp_del" }
func (*BierImpDel) GetCrcString() string            { return "7d45edf6" }
func (*BierImpDel) GetMessageType() api.MessageType { return api.RequestMessage }

// BierImpDelReply represents VPP binary API message 'bier_imp_del_reply'.
type BierImpDelReply struct {
	Retval int32
}

func (m *BierImpDelReply) Reset()                        { *m = BierImpDelReply{} }
func (*BierImpDelReply) GetMessageName() string          { return "bier_imp_del_reply" }
func (*BierImpDelReply) GetCrcString() string            { return "e8d4e804" }
func (*BierImpDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierImpDetails represents VPP binary API message 'bier_imp_details'.
type BierImpDetails struct {
	BiTblID  BierTableID
	BiSrc    uint16
	BiNBytes uint8 `struc:"sizeof=BiBytes"`
	BiBytes  []byte
}

func (m *BierImpDetails) Reset()                        { *m = BierImpDetails{} }
func (*BierImpDetails) GetMessageName() string          { return "bier_imp_details" }
func (*BierImpDetails) GetCrcString() string            { return "104b1f23" }
func (*BierImpDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierImpDump represents VPP binary API message 'bier_imp_dump'.
type BierImpDump struct{}

func (m *BierImpDump) Reset()                        { *m = BierImpDump{} }
func (*BierImpDump) GetMessageName() string          { return "bier_imp_dump" }
func (*BierImpDump) GetCrcString() string            { return "51077d14" }
func (*BierImpDump) GetMessageType() api.MessageType { return api.RequestMessage }

// BierRouteAddDel represents VPP binary API message 'bier_route_add_del'.
type BierRouteAddDel struct {
	BrBp        uint32
	BrIsAdd     uint8
	BrIsReplace uint8
	BrTblID     BierTableID
	BrNPaths    uint8 `struc:"sizeof=BrPaths"`
	BrPaths     []FibPath
}

func (m *BierRouteAddDel) Reset()                        { *m = BierRouteAddDel{} }
func (*BierRouteAddDel) GetMessageName() string          { return "bier_route_add_del" }
func (*BierRouteAddDel) GetCrcString() string            { return "0b83f5d2" }
func (*BierRouteAddDel) GetMessageType() api.MessageType { return api.RequestMessage }

// BierRouteAddDelReply represents VPP binary API message 'bier_route_add_del_reply'.
type BierRouteAddDelReply struct {
	Retval int32
}

func (m *BierRouteAddDelReply) Reset()                        { *m = BierRouteAddDelReply{} }
func (*BierRouteAddDelReply) GetMessageName() string          { return "bier_route_add_del_reply" }
func (*BierRouteAddDelReply) GetCrcString() string            { return "e8d4e804" }
func (*BierRouteAddDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierRouteDetails represents VPP binary API message 'bier_route_details'.
type BierRouteDetails struct {
	BrBp     uint16
	BrTblID  BierTableID
	BrNPaths uint32 `struc:"sizeof=BrPaths"`
	BrPaths  []FibPath
}

func (m *BierRouteDetails) Reset()                        { *m = BierRouteDetails{} }
func (*BierRouteDetails) GetMessageName() string          { return "bier_route_details" }
func (*BierRouteDetails) GetCrcString() string            { return "82c4087b" }
func (*BierRouteDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierRouteDump represents VPP binary API message 'bier_route_dump'.
type BierRouteDump struct {
	BrTblID BierTableID
}

func (m *BierRouteDump) Reset()                        { *m = BierRouteDump{} }
func (*BierRouteDump) GetMessageName() string          { return "bier_route_dump" }
func (*BierRouteDump) GetCrcString() string            { return "43af6370" }
func (*BierRouteDump) GetMessageType() api.MessageType { return api.RequestMessage }

// BierTableAddDel represents VPP binary API message 'bier_table_add_del'.
type BierTableAddDel struct {
	BtTblID BierTableID
	BtLabel uint32
	BtIsAdd uint8
}

func (m *BierTableAddDel) Reset()                        { *m = BierTableAddDel{} }
func (*BierTableAddDel) GetMessageName() string          { return "bier_table_add_del" }
func (*BierTableAddDel) GetCrcString() string            { return "4f7963b6" }
func (*BierTableAddDel) GetMessageType() api.MessageType { return api.RequestMessage }

// BierTableAddDelReply represents VPP binary API message 'bier_table_add_del_reply'.
type BierTableAddDelReply struct {
	Retval int32
}

func (m *BierTableAddDelReply) Reset()                        { *m = BierTableAddDelReply{} }
func (*BierTableAddDelReply) GetMessageName() string          { return "bier_table_add_del_reply" }
func (*BierTableAddDelReply) GetCrcString() string            { return "e8d4e804" }
func (*BierTableAddDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierTableDetails represents VPP binary API message 'bier_table_details'.
type BierTableDetails struct {
	BtLabel uint32
	BtTblID BierTableID
}

func (m *BierTableDetails) Reset()                        { *m = BierTableDetails{} }
func (*BierTableDetails) GetMessageName() string          { return "bier_table_details" }
func (*BierTableDetails) GetCrcString() string            { return "b7a41e40" }
func (*BierTableDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// BierTableDump represents VPP binary API message 'bier_table_dump'.
type BierTableDump struct{}

func (m *BierTableDump) Reset()                        { *m = BierTableDump{} }
func (*BierTableDump) GetMessageName() string          { return "bier_table_dump" }
func (*BierTableDump) GetCrcString() string            { return "51077d14" }
func (*BierTableDump) GetMessageType() api.MessageType { return api.RequestMessage }

func init() {
	api.RegisterMessage((*BierDispEntryAddDel)(nil), "bier.BierDispEntryAddDel")
	api.RegisterMessage((*BierDispEntryAddDelReply)(nil), "bier.BierDispEntryAddDelReply")
	api.RegisterMessage((*BierDispEntryDetails)(nil), "bier.BierDispEntryDetails")
	api.RegisterMessage((*BierDispEntryDump)(nil), "bier.BierDispEntryDump")
	api.RegisterMessage((*BierDispTableAddDel)(nil), "bier.BierDispTableAddDel")
	api.RegisterMessage((*BierDispTableAddDelReply)(nil), "bier.BierDispTableAddDelReply")
	api.RegisterMessage((*BierDispTableDetails)(nil), "bier.BierDispTableDetails")
	api.RegisterMessage((*BierDispTableDump)(nil), "bier.BierDispTableDump")
	api.RegisterMessage((*BierImpAdd)(nil), "bier.BierImpAdd")
	api.RegisterMessage((*BierImpAddReply)(nil), "bier.BierImpAddReply")
	api.RegisterMessage((*BierImpDel)(nil), "bier.BierImpDel")
	api.RegisterMessage((*BierImpDelReply)(nil), "bier.BierImpDelReply")
	api.RegisterMessage((*BierImpDetails)(nil), "bier.BierImpDetails")
	api.RegisterMessage((*BierImpDump)(nil), "bier.BierImpDump")
	api.RegisterMessage((*BierRouteAddDel)(nil), "bier.BierRouteAddDel")
	api.RegisterMessage((*BierRouteAddDelReply)(nil), "bier.BierRouteAddDelReply")
	api.RegisterMessage((*BierRouteDetails)(nil), "bier.BierRouteDetails")
	api.RegisterMessage((*BierRouteDump)(nil), "bier.BierRouteDump")
	api.RegisterMessage((*BierTableAddDel)(nil), "bier.BierTableAddDel")
	api.RegisterMessage((*BierTableAddDelReply)(nil), "bier.BierTableAddDelReply")
	api.RegisterMessage((*BierTableDetails)(nil), "bier.BierTableDetails")
	api.RegisterMessage((*BierTableDump)(nil), "bier.BierTableDump")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*BierDispEntryAddDel)(nil),
		(*BierDispEntryAddDelReply)(nil),
		(*BierDispEntryDetails)(nil),
		(*BierDispEntryDump)(nil),
		(*BierDispTableAddDel)(nil),
		(*BierDispTableAddDelReply)(nil),
		(*BierDispTableDetails)(nil),
		(*BierDispTableDump)(nil),
		(*BierImpAdd)(nil),
		(*BierImpAddReply)(nil),
		(*BierImpDel)(nil),
		(*BierImpDelReply)(nil),
		(*BierImpDetails)(nil),
		(*BierImpDump)(nil),
		(*BierRouteAddDel)(nil),
		(*BierRouteAddDelReply)(nil),
		(*BierRouteDetails)(nil),
		(*BierRouteDump)(nil),
		(*BierTableAddDel)(nil),
		(*BierTableAddDelReply)(nil),
		(*BierTableDetails)(nil),
		(*BierTableDump)(nil),
	}
}

// RPCService represents RPC service API for bier module.
type RPCService interface {
	DumpBierDispEntry(ctx context.Context, in *BierDispEntryDump) (RPCService_DumpBierDispEntryClient, error)
	DumpBierDispTable(ctx context.Context, in *BierDispTableDump) (RPCService_DumpBierDispTableClient, error)
	DumpBierImp(ctx context.Context, in *BierImpDump) (RPCService_DumpBierImpClient, error)
	DumpBierRoute(ctx context.Context, in *BierRouteDump) (RPCService_DumpBierRouteClient, error)
	DumpBierTable(ctx context.Context, in *BierTableDump) (RPCService_DumpBierTableClient, error)
	BierDispEntryAddDel(ctx context.Context, in *BierDispEntryAddDel) (*BierDispEntryAddDelReply, error)
	BierDispTableAddDel(ctx context.Context, in *BierDispTableAddDel) (*BierDispTableAddDelReply, error)
	BierImpAdd(ctx context.Context, in *BierImpAdd) (*BierImpAddReply, error)
	BierImpDel(ctx context.Context, in *BierImpDel) (*BierImpDelReply, error)
	BierRouteAddDel(ctx context.Context, in *BierRouteAddDel) (*BierRouteAddDelReply, error)
	BierTableAddDel(ctx context.Context, in *BierTableAddDel) (*BierTableAddDelReply, error)
}

type serviceClient struct {
	ch api.Channel
}

func NewServiceClient(ch api.Channel) RPCService {
	return &serviceClient{ch}
}

func (c *serviceClient) DumpBierDispEntry(ctx context.Context, in *BierDispEntryDump) (RPCService_DumpBierDispEntryClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpBierDispEntryClient{stream}
	return x, nil
}

type RPCService_DumpBierDispEntryClient interface {
	Recv() (*BierDispEntryDetails, error)
}

type serviceClient_DumpBierDispEntryClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpBierDispEntryClient) Recv() (*BierDispEntryDetails, error) {
	m := new(BierDispEntryDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) DumpBierDispTable(ctx context.Context, in *BierDispTableDump) (RPCService_DumpBierDispTableClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpBierDispTableClient{stream}
	return x, nil
}

type RPCService_DumpBierDispTableClient interface {
	Recv() (*BierDispTableDetails, error)
}

type serviceClient_DumpBierDispTableClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpBierDispTableClient) Recv() (*BierDispTableDetails, error) {
	m := new(BierDispTableDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) DumpBierImp(ctx context.Context, in *BierImpDump) (RPCService_DumpBierImpClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpBierImpClient{stream}
	return x, nil
}

type RPCService_DumpBierImpClient interface {
	Recv() (*BierImpDetails, error)
}

type serviceClient_DumpBierImpClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpBierImpClient) Recv() (*BierImpDetails, error) {
	m := new(BierImpDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) DumpBierRoute(ctx context.Context, in *BierRouteDump) (RPCService_DumpBierRouteClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpBierRouteClient{stream}
	return x, nil
}

type RPCService_DumpBierRouteClient interface {
	Recv() (*BierRouteDetails, error)
}

type serviceClient_DumpBierRouteClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpBierRouteClient) Recv() (*BierRouteDetails, error) {
	m := new(BierRouteDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) DumpBierTable(ctx context.Context, in *BierTableDump) (RPCService_DumpBierTableClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpBierTableClient{stream}
	return x, nil
}

type RPCService_DumpBierTableClient interface {
	Recv() (*BierTableDetails, error)
}

type serviceClient_DumpBierTableClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpBierTableClient) Recv() (*BierTableDetails, error) {
	m := new(BierTableDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) BierDispEntryAddDel(ctx context.Context, in *BierDispEntryAddDel) (*BierDispEntryAddDelReply, error) {
	out := new(BierDispEntryAddDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BierDispTableAddDel(ctx context.Context, in *BierDispTableAddDel) (*BierDispTableAddDelReply, error) {
	out := new(BierDispTableAddDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BierImpAdd(ctx context.Context, in *BierImpAdd) (*BierImpAddReply, error) {
	out := new(BierImpAddReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BierImpDel(ctx context.Context, in *BierImpDel) (*BierImpDelReply, error) {
	out := new(BierImpDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BierRouteAddDel(ctx context.Context, in *BierRouteAddDel) (*BierRouteAddDelReply, error) {
	out := new(BierRouteAddDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BierTableAddDel(ctx context.Context, in *BierTableAddDel) (*BierTableAddDelReply, error) {
	out := new(BierTableAddDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
